### ISSUE TITLE
Improve python worker documentation

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [media-cloud-ai/mcai_worker_sdk#100]
Improve [this file](https://github.com/media-cloud-ai/mcai_worker_sdk/blob/master/py_mcai_worker_sdk/worker.py)

- split into 2 sample files: `worker.py` and `media_worker.py`, it will be better for someone new.
- provide an example to add filter (like crop, resize and other) in the `media_worker.py`

**Comment by valnoel** [comment]
Fixed with 88782c1a3a42bc6a6510f78fcc2f2f21886b9efc
